version: '3'
services:
  app:
    build: .
    ports:
    - "80:8000"
    depends_on:
    - postgres
  postgres:
    image: postgres:15-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
